#!/bin/bash

if [ ! -f ubuntu-20.04.3-live-server-amd64.iso ]
then
    wget http://releases.ubuntu.com/20.04/ubuntu-20.04.3-live-server-amd64.iso -o ubuntu-20.04.3-live-server-amd64.iso
else
    echo "Skipping ISO download (already exists)"
fi

if [ ! -f ubuntu_base.qcow2 ]
then
    qemu-img create -f qcow2 ubuntu_base.qcow2 50G
else
    echo "Skipping FS creation (already exists)"
fi

qemu-system-x86_64 -boot d -cdrom ubuntu-20.04.3-live-server-amd64.iso -m 4096 -hda ubuntu_base.qcow2